---
title: "NWEA 2015 Norms"
author: "Chris Haid"
date: "June 24, 2015"
output: ioslides_presentation
runtime: shiny
---


```{r pre-reqs, echo=FALSE, include=FALSE}
require(ggplot2)
require(dplyr)

data("norms_students_2011", package="mapvisuals")
norms_students_2015 <- readr::read_csv("2015_Norms.csv")

n2015<-norms_students_2015 %>%
  mutate(Student_StartRIT = round(Student_StartRIT),
         Student_Growth = round(Student_Growth),
         Norms = 2015) %>%
  select(-6) %>%
  unique
  

n2011<-norms_students_2011 %>% 
  select(Subject = MeasurementScale,
         Grade = StartGrade,
         Student_StartRIT = StartRIT,
         Student_Growth=R22) %>%
  mutate(Norms = 2011) %>%
  inner_join(n2015 %>%
               select(Grade,
                      Subject,
                      Student_StartRIT,
                      Percentile), 
             by=c("Grade", "Subject", "Student_StartRIT"))

norms<-rbind_list(n2015, n2011) %>%
  dplyr::mutate(Norms = factor(Norms))

ggplot(norms %>% filter(Percentile %in% seq(10,90, by=10)), aes(x=Percentile, y=Student_Growth)) +
  geom_bar(aes(fill=Norms), stat="identity", position = "dodge") +
  coord_flip() + 
  facet_grid(Grade~Subject) +
  theme_bw()

```


## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Slide with Interactive Plot

```{r, echo=FALSE}
inputPanel(
  selectInput("grades", label = "Grades", multiple = TRUE,
              choices = c(1,2,3,4,6,7,8), selected = c(1,2,3,4,6,7,8)),
  
  selectInput("norms", label = "Select Norms",
              choices = c(2011, 2015), multiple = TRUE,
              selected = c(2011, 2015))
)

renderPlot({
ggplot(norms %>% filter(Percentile %in% seq(10,90, by=10),
                        Grade %in% input$grades,
                        Norms %in% input$norms), 
       aes(x=Percentile, y=Student_Growth)) +
  geom_bar(aes(fill = Norms), 
           stat = "identity", position = "dodge") +
  coord_flip() + 
  facet_grid(Grade~Subject) +
  theme_bw()
  
})
```

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output

```{r}
summary(cars)
```


