expect_that(abstractSeasonNames(df = NULL, season1 = NULL, season2 = NULL, new1 = NULL, new2 = NULL), equals(NULL))
expect_that(get_MAPResults(connection = NULL, season1 = NULL, season2 = NULL), equals(NULL))
expect_that(PrepMAP(map.dt = NULL, season1 = NULL, season2 = NULL, growth.type = NULL), equals(NULL))
expect_that(abstractSeasonNames(df = NULL, season1 = NULL, season2 = NULL, new1 = NULL, new2 = NULL), equals(NULL))
expect_that(calc_quartile(dtable = NULL, percentile.column = NULL, quartile.col.name = NULL), equals(NULL))
expect_that(calc_tiered_growth(dt = NULL, quartile.column = NULL, grade.column = NULL), equals(NULL))
expect_that(get_group_stats(df = NULL, grp = NULL, RIT = NULL), equals(NULL))
expect_that(get_MAPResults(connection = NULL, season1 = NULL, season2 = NULL), equals(NULL))
expect_that(map_2011_simulated_distr(m = NULL, s = NULL), equals(NULL))
expect_that(map_combined_histo_data(kippdata = NULL, normsdata = NULL, grade = NULL, subj = NULL, schoolname = NULL), equals(NULL))
expect_that(map_comparative_histograms(df = NULL, legendpos = NULL, title = NULL, ... = NULL), equals(NULL))
expect_that(orderid(df = NULL, v1 = NULL), equals(NULL))
expect_that(pdf_waterfall(.data = NULL, school = NULL, season1 = NULL, season2 = NULL), equals(NULL))
expect_that(plot_waterfall(df = NULL, plottitle = NULL, season1 = NULL, season2 = NULL, tiered.growth = NULL, labxpos = NULL, minx = NULL, alp = NULL), equals(NULL))
expect_that(PrepMAP(map.dt = NULL, season1 = NULL, season2 = NULL, growth.type = NULL), equals(NULL))
